apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: to76o1c7v-python 
  janus-idp.io/tekton: to76o1c7v-python
  backstage.io/kubernetes-id: to76o1c7v-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: to76o1c7v-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  